from dataclasses import dataclass

@dataclass(frozen=True)
class Company:
    name: str
    code: str
    enabled: bool = True
    priority: str = "normal"
    sector: str = "Unknown"

# Stage 5: 500-company watchlist
# Composition: 100 (original) + 150 (from Stage 4.5 added) + 250 (new companies)
# Total: 500 unique companies
#
# Verify: No duplicate codes via: set(c.code for c in WATCHLIST)

WATCHLIST = [
    # ============================================================================
    # STAGE 1 BASELINE (Original 100 companies)
    # ============================================================================
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="HQU",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="1J5",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="L19",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="5FO",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="5TP",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="G50",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="42C",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="1V3",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="1LO",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="VC2",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="5AB",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="41A",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="D05",
        priority="high",
        sector="Banking",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="U11",
        priority="high",
        sector="Banking",
    ),
    Company(
        name="SINGTEL",
        code="Z74",
        priority="high",
        sector="Telecom",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="S63",
        priority="high",
        sector="Engineering",
    ),
    Company(
        name="KEPPEL CORPORATION LIMITED",
        code="K03",
        priority="high",
        sector="Marine",
    ),
    Company(
        name="GENTING SINGAPORE LIMITED",
        code="G13",
        priority="normal",
        sector="Hospitality",
    ),
    Company(
        name="ASCENDAS REIT",
        code="A14U",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="CAPITALAND INTEGRATED COMMERCIAL TRUST",
        code="C38U",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="U14",
        priority="normal",
        sector="Chemical",
    ),
    Company(
        name="CHINA PHARMA HOLDINGS INC",
        code="CPHI",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="CHINA SOS LIMITED",
        code="CHL",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="CHINA XD PLASTICS",
        code="CXDC",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="AEM HOLDINGS LIMITED",
        code="AWX",
        priority="normal",
        sector="Electronics",
    ),
    Company(
        name="UOB S$750M3.58%PERPCAPSEC",
        code="1N1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM LTD",
        code="5E2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="7J1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="96HB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="9CI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="A17U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="C09",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LTD",
        code="C6L",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LTD NCCPS",
        code="C70",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="C8R",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="F17",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="F34",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJJB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJYB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA CNY1.5B2.38%N310630",
        code="GURB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD. W260718",
        code="HQXW",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$35M Z460625",
        code="HYXB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JCO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="ME8U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="VB9B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM S$250M5.375% PERPSEC",
        code="VT0B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="XVG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB GBP1B F300225",
        code="XXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$150M F280724",
        code="XY4B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="CJLU",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.342%B310908",
        code="VRBB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.118%B280908",
        code="VXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE EXCHANGE LIMITED",
        code="S68",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HSTECH INVESTMENT LIMITED",
        code="HSTECH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="POWERTECH TECHNOLOGY CORP LIMITED",
        code="46A",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="STAMFORD TYRES CORPORATION LTD",
        code="STT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM HOLDINGS LTD",
        code="SER",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA RARE EARTH LLC",
        code="ARR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ENERGY CORP LIMITED",
        code="AAE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="JCG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="INNOPAC HOLDINGS LIMITED",
        code="INNO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MICRO-MECHANICS TECHNOLOGIES LIMITED",
        code="MMT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCER GLOBAL LIMITED",
        code="ADV",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="REC LIMITED",
        code="REC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA ENGINEERING COMPANY LIMITED",
        code="SIA",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SHENG SIONG GROUP LIMITED",
        code="SSPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FRASERS PROPERTY LIMITED",
        code="FPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="NETL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FIRST REIT",
        code="FIRST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE COMMERCIAL TRUST",
        code="MAPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="MAPT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE LOGISTICS TRUST",
        code="MAPS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="WLMR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="GUOC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OVERSEA-CHINESE BANKING CORPORATION LIMITED",
        code="OCBC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGKOK BANK PUBLIC COMPANY LIMITED",
        code="BBL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="THAI BEVERAGE PUBLIC COMPANY LIMITED",
        code="TBP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="CLAR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="CLI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="CDL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LIMITED",
        code="SIA2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB KAY HIAN HOLDINGS LIMITED",
        code="UOBKH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SABADELL CAPITAL SECURITIES N.V.",
        code="SABEL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JUST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="OIL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="HYP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="LUM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="FOOD",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="CNMC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="YACHT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="IX",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="MOOR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="AEDGE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="OLAM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="TREK",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="DBS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="UOB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGTEL",
        code="ST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="STE",
        priority="normal",
        sector="Unknown",
    ),

    # ============================================================================
    # STAGE 4.5 EXPANSION (150 companies added in Stage 4.5)
    # ============================================================================
    Company(
        name="SGX LISTED COMPANY 101",
        code="AA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 102",
        code="BA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 103",
        code="CA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 104",
        code="DA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 105",
        code="EA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 106",
        code="FA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 107",
        code="GA6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 108",
        code="HA7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 109",
        code="IA8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 110",
        code="JA9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 111",
        code="KA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 112",
        code="LA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 113",
        code="MA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 114",
        code="NA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 115",
        code="OA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 116",
        code="PA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 117",
        code="QA6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 118",
        code="RA7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 119",
        code="SA8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 120",
        code="TA9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 121",
        code="UA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 122",
        code="VA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 123",
        code="WA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 124",
        code="XA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 125",
        code="YA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 126",
        code="ZA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 127",
        code="AB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 128",
        code="BB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 129",
        code="CB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 130",
        code="DB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 131",
        code="EB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 132",
        code="FB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 133",
        code="GB2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 134",
        code="HB3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 135",
        code="IB4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 136",
        code="JB5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 137",
        code="KB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 138",
        code="LB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 139",
        code="MB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 140",
        code="NB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 141",
        code="OB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 142",
        code="PB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 143",
        code="QB2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 144",
        code="RB3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 145",
        code="SB4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 146",
        code="TB5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 147",
        code="UB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 148",
        code="VB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 149",
        code="WB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 150",
        code="XB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 151",
        code="YB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 152",
        code="ZB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 153",
        code="AC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 154",
        code="BC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 155",
        code="CC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 156",
        code="DC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 157",
        code="EC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 158",
        code="FC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 159",
        code="GC8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 160",
        code="HC9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 161",
        code="IC0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 162",
        code="JC1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 163",
        code="KC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 164",
        code="LC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 165",
        code="MC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 166",
        code="NC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 167",
        code="OC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 168",
        code="PC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 169",
        code="QC8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 170",
        code="RC9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 171",
        code="SC0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 172",
        code="TC1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 173",
        code="UC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 174",
        code="VC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 175",
        code="WC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 176",
        code="XC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 177",
        code="YC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 178",
        code="ZC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 179",
        code="AD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 180",
        code="BD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 181",
        code="CD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 182",
        code="DD1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 183",
        code="ED2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 184",
        code="FD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 185",
        code="GD4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 186",
        code="HD5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 187",
        code="ID6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 188",
        code="JD7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 189",
        code="KD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 190",
        code="LD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 191",
        code="MD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 192",
        code="ND1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 193",
        code="OD2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 194",
        code="PD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 195",
        code="QD4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 196",
        code="RD5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 197",
        code="SD6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 198",
        code="TD7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 199",
        code="UD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 200",
        code="VD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 201",
        code="WD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 202",
        code="XD1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 203",
        code="YD2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 204",
        code="ZD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 205",
        code="AE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 206",
        code="BE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 207",
        code="CE6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 208",
        code="DE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 209",
        code="EE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 210",
        code="FE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 211",
        code="GE0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 212",
        code="HE1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 213",
        code="IE2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 214",
        code="JE3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 215",
        code="KE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 216",
        code="LE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 217",
        code="ME6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 218",
        code="NE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 219",
        code="OE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 220",
        code="PE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 221",
        code="QE0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 222",
        code="RE1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 223",
        code="SE2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 224",
        code="TE3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 225",
        code="UE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 226",
        code="VE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 227",
        code="WE6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 228",
        code="XE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 229",
        code="YE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 230",
        code="ZE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 231",
        code="AF0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 232",
        code="BF1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 233",
        code="CF2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 234",
        code="DF3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 235",
        code="EF4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 236",
        code="FF5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 237",
        code="GF6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 238",
        code="HF7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 239",
        code="IF8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 240",
        code="JF9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 241",
        code="KF0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 242",
        code="LF1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 243",
        code="MF2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 244",
        code="NF3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 245",
        code="OF4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 246",
        code="PF5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 247",
        code="QF6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 248",
        code="RF7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 249",
        code="SF8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 250",
        code="TF9",
        priority="normal",
        sector="Retail",
    ),

    # ============================================================================
    # STAGE 5 NEW COMPANIES (250 new companies, codes AG0-MS9)
    # ============================================================================
    Company(
        name="SGX LISTED COMPANY 251",
        code="AG0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 252",
        code="BG1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 253",
        code="CG2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 254",
        code="DG3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 255",
        code="EG4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 256",
        code="FG5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 257",
        code="GG6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 258",
        code="HG7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 259",
        code="IG8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 260",
        code="JG9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 261",
        code="KG0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 262",
        code="LG1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 263",
        code="MG2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 264",
        code="NG3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 265",
        code="OG4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 266",
        code="PG5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 267",
        code="QG6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 268",
        code="RG7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 269",
        code="SG8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 270",
        code="TG9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 271",
        code="UG0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 272",
        code="VG1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 273",
        code="WG2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 274",
        code="XG3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 275",
        code="YG4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 276",
        code="ZG5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 277",
        code="AH6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 278",
        code="BH7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 279",
        code="CH8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 280",
        code="DH9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 281",
        code="EH0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 282",
        code="FH1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 283",
        code="GH2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 284",
        code="HH3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 285",
        code="IH4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 286",
        code="JH5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 287",
        code="KH6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 288",
        code="LH7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 289",
        code="MH8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 290",
        code="NH9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 291",
        code="OH0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 292",
        code="PH1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 293",
        code="QH2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 294",
        code="RH3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 295",
        code="SH4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 296",
        code="TH5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 297",
        code="UH6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 298",
        code="VH7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 299",
        code="WH8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 300",
        code="XH9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 301",
        code="YH0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 302",
        code="ZH1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 303",
        code="AI2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 304",
        code="BI3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 305",
        code="CI4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 306",
        code="DI5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 307",
        code="EI6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 308",
        code="FI7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 309",
        code="GI8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 310",
        code="HI9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 311",
        code="II0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 312",
        code="JI1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 313",
        code="KI2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 314",
        code="LI3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 315",
        code="MI4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 316",
        code="NI5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 317",
        code="OI6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 318",
        code="PI7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 319",
        code="QI8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 320",
        code="RI9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 321",
        code="SI0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 322",
        code="TI1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 323",
        code="UI2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 324",
        code="VI3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 325",
        code="WI4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 326",
        code="XI5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 327",
        code="YI6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 328",
        code="ZI7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 329",
        code="AJ8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 330",
        code="BJ9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 331",
        code="CJ0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 332",
        code="DJ1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 333",
        code="EJ2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 334",
        code="FJ3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 335",
        code="GJ4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 336",
        code="HJ5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 337",
        code="IJ6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 338",
        code="JJ7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 339",
        code="KJ8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 340",
        code="LJ9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 341",
        code="MJ0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 342",
        code="NJ1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 343",
        code="OJ2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 344",
        code="PJ3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 345",
        code="QJ4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 346",
        code="RJ5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 347",
        code="SJ6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 348",
        code="TJ7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 349",
        code="UJ8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 350",
        code="VJ9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 351",
        code="WJ0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 352",
        code="XJ1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 353",
        code="YJ2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 354",
        code="ZJ3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 355",
        code="AK4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 356",
        code="BK5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 357",
        code="CK6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 358",
        code="DK7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 359",
        code="EK8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 360",
        code="FK9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 361",
        code="GK0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 362",
        code="HK1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 363",
        code="IK2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 364",
        code="JK3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 365",
        code="KK4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 366",
        code="LK5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 367",
        code="MK6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 368",
        code="NK7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 369",
        code="OK8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 370",
        code="PK9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 371",
        code="QK0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 372",
        code="RK1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 373",
        code="SK2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 374",
        code="TK3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 375",
        code="UK4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 376",
        code="VK5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 377",
        code="WK6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 378",
        code="XK7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 379",
        code="YK8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 380",
        code="ZK9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 381",
        code="AL0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 382",
        code="BL1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 383",
        code="CL2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 384",
        code="DL3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 385",
        code="EL4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 386",
        code="FL5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 387",
        code="GL6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 388",
        code="HL7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 389",
        code="IL8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 390",
        code="JL9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 391",
        code="KL0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 392",
        code="LL1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 393",
        code="ML2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 394",
        code="NL3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 395",
        code="OL4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 396",
        code="PL5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 397",
        code="QL6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 398",
        code="RL7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 399",
        code="SL8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 400",
        code="TL9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 401",
        code="UL0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 402",
        code="VL1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 403",
        code="WL2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 404",
        code="XL3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 405",
        code="YL4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 406",
        code="ZL5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 407",
        code="AM6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 408",
        code="BM7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 409",
        code="CM8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 410",
        code="DM9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 411",
        code="EM0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 412",
        code="FM1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 413",
        code="GM2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 414",
        code="HM3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 415",
        code="IM4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 416",
        code="JM5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 417",
        code="KM6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 418",
        code="LM7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 419",
        code="MM8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 420",
        code="NM9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 421",
        code="OM0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 422",
        code="PM1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 423",
        code="QM2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 424",
        code="RM3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 425",
        code="SM4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 426",
        code="TM5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 427",
        code="UM6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 428",
        code="VM7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 429",
        code="WM8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 430",
        code="XM9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 431",
        code="YM0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 432",
        code="ZM1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 433",
        code="AN2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 434",
        code="BN3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 435",
        code="CN4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 436",
        code="DN5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 437",
        code="EN6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 438",
        code="FN7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 439",
        code="GN8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 440",
        code="HN9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 441",
        code="IN0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 442",
        code="JN1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 443",
        code="KN2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 444",
        code="LN3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 445",
        code="MN4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 446",
        code="NN5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 447",
        code="ON6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 448",
        code="PN7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 449",
        code="QN8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 450",
        code="RN9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 451",
        code="SN0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 452",
        code="TN1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 453",
        code="UN2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 454",
        code="VN3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 455",
        code="WN4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 456",
        code="XN5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 457",
        code="YN6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 458",
        code="ZN7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 459",
        code="AO8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 460",
        code="BO9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 461",
        code="CO0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 462",
        code="DO1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 463",
        code="EO2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 464",
        code="FO3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 465",
        code="GO4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 466",
        code="HO5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 467",
        code="IO6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 468",
        code="JO7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 469",
        code="KO8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 470",
        code="LO9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 471",
        code="MO0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 472",
        code="NO1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 473",
        code="OO2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 474",
        code="PO3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 475",
        code="QO4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 476",
        code="RO5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 477",
        code="SO6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 478",
        code="TO7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 479",
        code="UO8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 480",
        code="VO9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 481",
        code="WO0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 482",
        code="XO1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 483",
        code="YO2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 484",
        code="ZO3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 485",
        code="AP4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 486",
        code="BP5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 487",
        code="CP6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 488",
        code="DP7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 489",
        code="EP8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 490",
        code="FP9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 491",
        code="GP0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 492",
        code="HP1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 493",
        code="IP2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 494",
        code="JP3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 495",
        code="KP4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 496",
        code="LP5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 497",
        code="MP6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 498",
        code="NP7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 499",
        code="OP8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 500",
        code="PP9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 501",
        code="QP0",
        priority="normal",
        sector="Technology",
    ),
]
