from dataclasses import dataclass

@dataclass(frozen=True)
class Company:
    name: str
    code: str
    enabled: bool = True
    priority: str = "normal"
    sector: str = "Unknown"

WATCHLIST = [
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="HQU",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="1J5",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="L19",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="5FO",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="5TP",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="G50",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="42C",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="1V3",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="1LO",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="VC2",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="5AB",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="41A",
        priority="high",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="D05",
        priority="high",
        sector="Banking",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="U11",
        priority="high",
        sector="Banking",
    ),
    Company(
        name="SINGTEL",
        code="Z74",
        priority="high",
        sector="Telecom",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="S63",
        priority="high",
        sector="Engineering",
    ),
    Company(
        name="KEPPEL CORPORATION LIMITED",
        code="K03",
        priority="high",
        sector="Marine",
    ),
    Company(
        name="GENTING SINGAPORE LIMITED",
        code="G13",
        priority="normal",
        sector="Hospitality",
    ),
    Company(
        name="ASCENDAS REIT",
        code="A14U",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="CAPITALAND INTEGRATED COMMERCIAL TRUST",
        code="C38U",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="U14",
        priority="normal",
        sector="Chemical",
    ),
    Company(
        name="CHINA PHARMA HOLDINGS INC",
        code="CPHI",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="CHINA SOS LIMITED",
        code="CHL",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="CHINA XD PLASTICS",
        code="CXDC",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="AEM HOLDINGS LIMITED",
        code="AWX",
        priority="normal",
        sector="Electronics",
    ),
    Company(
        name="UOB S$750M3.58%PERPCAPSEC",
        code="1N1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM LTD",
        code="5E2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="7J1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="96HB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="9CI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="A17U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="C09",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LTD",
        code="C6L",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LTD NCCPS",
        code="C70",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="C8R",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="F17",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="F34",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJJB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJYB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA CNY1.5B2.38%N310630",
        code="GURB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD. W260718",
        code="HQXW",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$35M Z460625",
        code="HYXB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JCO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="ME8U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="VB9B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM S$250M5.375% PERPSEC",
        code="VT0B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="XVG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB GBP1B F300225",
        code="XXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$150M F280724",
        code="XY4B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="CJLU",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.342%B310908",
        code="VRBB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.118%B280908",
        code="VXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE EXCHANGE LIMITED",
        code="S68",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HSTECH INVESTMENT LIMITED",
        code="HSTECH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="POWERTECH TECHNOLOGY CORP LIMITED",
        code="46A",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="STAMFORD TYRES CORPORATION LTD",
        code="STT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM LIMITED",
        code="5E2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA RARE EARTH LLC",
        code="ARR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ENERGY CORP LIMITED",
        code="AAE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="JCG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CHINA SOS LIMITED",
        code="CHL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="INNOPAC HOLDINGS LIMITED",
        code="INNO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MICRO-MECHANICS TECHNOLOGIES LIMITED",
        code="MMT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCER GLOBAL LIMITED",
        code="ADV",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="REC LIMITED",
        code="REC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA ENGINEERING COMPANY LIMITED",
        code="SIA",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SHENG SIONG GROUP LIMITED",
        code="SSPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FRASERS PROPERTY LIMITED",
        code="FPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="NETL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FIRST REIT",
        code="FIRST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE COMMERCIAL TRUST",
        code="MAPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="MAPT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE LOGISTICS TRUST",
        code="MAPS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="WLMR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="GUOC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OVERSEA-CHINESE BANKING CORPORATION LIMITED",
        code="OCBC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGKOK BANK PUBLIC COMPANY LIMITED",
        code="BBL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="THAI BEVERAGE PUBLIC COMPANY LIMITED",
        code="TBP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="CLAR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="CLI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="CDL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LIMITED",
        code="SIA2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB KAY HIAN HOLDINGS LIMITED",
        code="UOBKH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SABADELL CAPITAL SECURITIES N.V.",
        code="SABEL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JUST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="OIL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="HYP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="LUM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="FOOD",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="CNMC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="YACHT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="IX",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="MOOR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="AEDGE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="OLAM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="TREK",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="DBS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="UOB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGTEL",
        code="ST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="STE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SGX LISTED COMPANY 101",
        code="AA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 102",
        code="BA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 103",
        code="CA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 104",
        code="DA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 105",
        code="EA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 106",
        code="FA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 107",
        code="GA6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 108",
        code="HA7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 109",
        code="IA8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 110",
        code="JA9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 111",
        code="KA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 112",
        code="LA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 113",
        code="MA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 114",
        code="NA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 115",
        code="OA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 116",
        code="PA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 117",
        code="QA6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 118",
        code="RA7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 119",
        code="SA8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 120",
        code="TA9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 121",
        code="UA0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 122",
        code="VA1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 123",
        code="WA2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 124",
        code="XA3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 125",
        code="YA4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 126",
        code="ZA5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 127",
        code="AB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 128",
        code="BB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 129",
        code="CB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 130",
        code="DB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 131",
        code="EB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 132",
        code="FB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 133",
        code="GB2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 134",
        code="HB3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 135",
        code="IB4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 136",
        code="JB5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 137",
        code="KB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 138",
        code="LB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 139",
        code="MB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 140",
        code="NB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 141",
        code="OB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 142",
        code="PB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 143",
        code="QB2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 144",
        code="RB3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 145",
        code="SB4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 146",
        code="TB5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 147",
        code="UB6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 148",
        code="VB7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 149",
        code="WB8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 150",
        code="XB9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 151",
        code="YB0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 152",
        code="ZB1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 153",
        code="AC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 154",
        code="BC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 155",
        code="CC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 156",
        code="DC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 157",
        code="EC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 158",
        code="FC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 159",
        code="GC8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 160",
        code="HC9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 161",
        code="IC0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 162",
        code="JC1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 163",
        code="KC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 164",
        code="LC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 165",
        code="MC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 166",
        code="NC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 167",
        code="OC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 168",
        code="PC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 169",
        code="QC8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 170",
        code="RC9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 171",
        code="SC0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 172",
        code="TC1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 173",
        code="UC2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 174",
        code="VC3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 175",
        code="WC4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 176",
        code="XC5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 177",
        code="YC6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 178",
        code="ZC7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 179",
        code="AD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 180",
        code="BD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 181",
        code="CD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 182",
        code="DD1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 183",
        code="ED2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 184",
        code="FD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 185",
        code="GD4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 186",
        code="HD5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 187",
        code="ID6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 188",
        code="JD7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 189",
        code="KD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 190",
        code="LD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 191",
        code="MD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 192",
        code="ND1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 193",
        code="OD2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 194",
        code="PD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 195",
        code="QD4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 196",
        code="RD5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 197",
        code="SD6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 198",
        code="TD7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 199",
        code="UD8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 200",
        code="VD9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 201",
        code="WD0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 202",
        code="XD1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 203",
        code="YD2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 204",
        code="ZD3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 205",
        code="AE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 206",
        code="BE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 207",
        code="CE6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 208",
        code="DE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 209",
        code="EE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 210",
        code="FE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 211",
        code="GE0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 212",
        code="HE1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 213",
        code="IE2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 214",
        code="JE3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 215",
        code="KE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 216",
        code="LE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 217",
        code="ME6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 218",
        code="NE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 219",
        code="OE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 220",
        code="PE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 221",
        code="QE0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 222",
        code="RE1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 223",
        code="SE2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 224",
        code="TE3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 225",
        code="UE4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 226",
        code="VE5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 227",
        code="WE6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 228",
        code="XE7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 229",
        code="YE8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 230",
        code="ZE9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 231",
        code="AF0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 232",
        code="BF1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 233",
        code="CF2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 234",
        code="DF3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 235",
        code="EF4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 236",
        code="FF5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 237",
        code="GF6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 238",
        code="HF7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 239",
        code="IF8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 240",
        code="JF9",
        priority="normal",
        sector="Retail",
    ),
    Company(
        name="SGX LISTED COMPANY 241",
        code="KF0",
        priority="normal",
        sector="Technology",
    ),
    Company(
        name="SGX LISTED COMPANY 242",
        code="LF1",
        priority="normal",
        sector="Healthcare",
    ),
    Company(
        name="SGX LISTED COMPANY 243",
        code="MF2",
        priority="normal",
        sector="Finance",
    ),
    Company(
        name="SGX LISTED COMPANY 244",
        code="NF3",
        priority="normal",
        sector="Manufacturing",
    ),
    Company(
        name="SGX LISTED COMPANY 245",
        code="OF4",
        priority="normal",
        sector="Energy",
    ),
    Company(
        name="SGX LISTED COMPANY 246",
        code="PF5",
        priority="normal",
        sector="Transport",
    ),
    Company(
        name="SGX LISTED COMPANY 247",
        code="QF6",
        priority="normal",
        sector="Real Estate",
    ),
    Company(
        name="SGX LISTED COMPANY 248",
        code="RF7",
        priority="normal",
        sector="Consumer",
    ),
    Company(
        name="SGX LISTED COMPANY 249",
        code="SF8",
        priority="normal",
        sector="Telecom",
    ),
    Company(
        name="SGX LISTED COMPANY 250",
        code="TF9",
        priority="normal",
        sector="Retail",
    ),
]
