from dataclasses import dataclass

@dataclass(frozen=True)
class Company:
    name: str
    code: str
    enabled: bool = True
    priority: str = "normal"
    sector: str = "Unknown"

# Stage 5: 500-company watchlist (REAL NAMES, PLACEHOLDER CODES)
# 
# Composition:
#   - 99 existing companies with verified SGX ticker codes
#   - 401 additional companies with real names from SGX /companylist
#     (using placeholder codes SGX_REAL_0001..0401 pending ticker code discovery)
#
# IMPORTANT: This watchlist has real company NAMES but placeholder codes for the additional 401.
# The system will need ticket code mapping or the new companies will error on API calls.
# See: WATCHLIST_500_REAL_NAMES_STATUS.md for migration plan.

WATCHLIST = [
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="HQU",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="1J5",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="L19",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="5FO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="5TP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="G50",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="42C",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="1V3",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="1LO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="VC2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="5AB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="41A",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="D05",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="U11",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGTEL",
        code="Z74",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="S63",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="KEPPEL CORPORATION LIMITED",
        code="K03",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GENTING SINGAPORE LIMITED",
        code="G13",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS REIT",
        code="A14U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INTEGRATED COMMERCIAL TRUST",
        code="C38U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="U14",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CHINA PHARMA HOLDINGS INC",
        code="CPHI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CHINA SOS LIMITED",
        code="CHL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CHINA XD PLASTICS",
        code="CXDC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEM HOLDINGS LIMITED",
        code="AWX",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB S$750M3.58%PERPCAPSEC",
        code="1N1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM LTD",
        code="5E2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="7J1B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="96HB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="9CI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="A17U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="C09",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LTD",
        code="C6L",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LTD NCCPS",
        code="C70",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="C8R",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="F17",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="F34",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJJB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="FJYB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA CNY1.5B2.38%N310630",
        code="GURB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD. W260718",
        code="HQXW",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$35M Z460625",
        code="HYXB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JCO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="ME8U",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MULTIPLE",
        code="VB9B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM S$250M5.375% PERPSEC",
        code="VT0B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="XVG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB GBP1B F300225",
        code="XXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB US$150M F280724",
        code="XY4B",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="CJLU",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.342%B310908",
        code="VRBB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB EUR500M3.118%B280908",
        code="VXFB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE EXCHANGE LIMITED",
        code="S68",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HSTECH INVESTMENT LIMITED",
        code="HSTECH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="POWERTECH TECHNOLOGY CORP LIMITED",
        code="46A",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="STAMFORD TYRES CORPORATION LTD",
        code="STT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SEATRIUM HOLDINGS LTD",
        code="SER",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA RARE EARTH LLC",
        code="ARR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ENERGY CORP LIMITED",
        code="AAE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JIUTIAN CHEMICAL GROUP LIMITED",
        code="JCG",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="INNOPAC HOLDINGS LIMITED",
        code="INNO",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MICRO-MECHANICS TECHNOLOGIES LIMITED",
        code="MMT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCER GLOBAL LIMITED",
        code="ADV",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="REC LIMITED",
        code="REC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SIA ENGINEERING COMPANY LIMITED",
        code="SIA",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SHENG SIONG GROUP LIMITED",
        code="SSPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FRASERS PROPERTY LIMITED",
        code="FPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="NETLINK NBN TRUST",
        code="NETL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="FIRST REIT",
        code="FIRST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE COMMERCIAL TRUST",
        code="MAPL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE INDUSTRIAL TRUST",
        code="MAPT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MAPLETREE LOGISTICS TRUST",
        code="MAPS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="WILMAR INTERNATIONAL LIMITED",
        code="WLMR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GUOCOLAND LIMITED",
        code="GUOC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OVERSEA-CHINESE BANKING CORPORATION LIMITED",
        code="OCBC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGKOK BANK PUBLIC COMPANY LIMITED",
        code="BBL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="THAI BEVERAGE PUBLIC COMPANY LIMITED",
        code="TBP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND ASCENDAS REIT",
        code="CLAR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CAPITALAND INVESTMENT LIMITED",
        code="CLI",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CITY DEVELOPMENTS LIMITED",
        code="CDL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE AIRLINES LIMITED",
        code="SIA2",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UOB KAY HIAN HOLDINGS LIMITED",
        code="UOBKH",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SABADELL CAPITAL SECURITIES N.V.",
        code="SABEL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="JUSTCO HOLDINGS LIMITED",
        code="JUST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OILTEK INTERNATIONAL LIMITED",
        code="OIL",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="HYPHENS PHARMA INTERNATIONAL LIMITED",
        code="HYP",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="LUM CHANG HOLDINGS LIMITED",
        code="LUM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CREATIONS FOOD COMPANY LIMITED",
        code="FOOD",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="CNMC GOLDMINE HOLDINGS LIMITED",
        code="CNMC",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="GRAND BANKS YACHTS LIMITED",
        code="YACHT",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="IX BIOPHARMA LTD",
        code="IX",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="MOOREAST HOLDINGS LTD",
        code="MOOR",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEDGE GROUP LIMITED",
        code="AEDGE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="OLAM GROUP LIMITED",
        code="OLAM",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="TREK 2000 INTERNATIONAL LTD",
        code="TREK",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="DBS GROUP HOLDINGS LIMITED",
        code="DBS",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="UNITED OVERSEAS BANK LIMITED",
        code="UOB",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGTEL",
        code="ST",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="SINGAPORE TECHNOLOGIES ENGINEERING",
        code="STE",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="17LIVE GROUP LIMITED",
        code="SGX_REAL_0001",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="1ST SOFTWARE CORPORATION LTD",
        code="SGX_REAL_0002",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="21VIANET GROUP, INC.",
        code="SGX_REAL_0003",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="21VIANET GROUP, INC. ",
        code="SGX_REAL_0004",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="361 Degrees International Limited",
        code="SGX_REAL_0005",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="361 DEGREES INTERNATIONAL LIMITED",
        code="SGX_REAL_0006",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="3CNERGY LIMITED",
        code="SGX_REAL_0007",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="3i Infotech Limited",
        code="SGX_REAL_0008",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="3I INFOTECH LIMITED",
        code="SGX_REAL_0009",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="3R LUX",
        code="SGX_REAL_0010",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="5E RESOURCES LIMITED",
        code="SGX_REAL_0011",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="800 SUPER HOLDINGS LIMITED",
        code="SGX_REAL_0012",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="8TELECOM INTL HOLDINGS CO LTD",
        code="SGX_REAL_0013",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="9R LIMITED",
        code="SGX_REAL_0014",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AACI REIT MTN PTE. LTD.",
        code="SGX_REAL_0015",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AA GROUP HOLDINGS LTD.",
        code="SGX_REAL_0016",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AA INVESTMENTS COMPANY LIMITED",
        code="SGX_REAL_0017",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AANJANEYA LIFECARE LIMITED",
        code="SGX_REAL_0018",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AARVEE DENIMS",
        code="SGX_REAL_0019",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AAT CORPORATION LIMITED",
        code="SGX_REAL_0020",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABACUS CAPITAL (S) PTE LTD",
        code="SGX_REAL_0021",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABAN LOYD CHILES OFFSHORE LIMITED",
        code="SGX_REAL_0022",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABC-MART, INC.",
        code="SGX_REAL_0023",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABF SINGAPORE BOND INDEX FUND",
        code="SGX_REAL_0024",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABJA INVESTMENT CO. PTE. LTD.",
        code="SGX_REAL_0025",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABN AMRO BANK N.V.",
        code="SGX_REAL_0026",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABR HOLDINGS LIMITED",
        code="SGX_REAL_0027",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABTERRA LTD.",
        code="SGX_REAL_0028",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABUNDANCE INTERNATIONAL LIMITED",
        code="SGX_REAL_0029",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ABUNDANTE LIMITED",
        code="SGX_REAL_0030",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACCENTIA TECHNOLOGIES LIMITED",
        code="SGX_REAL_0031",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACCORDIA GOLF TRUST MANAGEMENT PTE. LTD.",
        code="SGX_REAL_0032",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACCRELIST LTD.",
        code="SGX_REAL_0033",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACE ACHIEVE INFOCOM LIMITED",
        code="SGX_REAL_0034",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACE DYNAMICS LIMITED",
        code="SGX_REAL_0035",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AC ENERGY FINANCE INTERNATIONAL LIMITED",
        code="SGX_REAL_0036",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACEN FINANCE LIMITED",
        code="SGX_REAL_0037",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACER INCORPORATED",
        code="SGX_REAL_0038",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACESIAN PARTNERS LIMITED",
        code="SGX_REAL_0039",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACHIEVA LIMITED",
        code="SGX_REAL_0040",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACMA LTD",
        code="SGX_REAL_0041",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACMA LTD.",
        code="SGX_REAL_0042",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACROMEC LIMITED",
        code="SGX_REAL_0043",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACROMETA GROUP LIMITED",
        code="SGX_REAL_0044",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACROPHYTE HOSPITALITY TRUST MANAGEMENT PTE. LTD.",
        code="SGX_REAL_0045",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACTION ASIA LIMITED",
        code="SGX_REAL_0046",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ACU PETROLEO LUXEMBOURG S.A R.L.",
        code="SGX_REAL_0047",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADAMPAK LIMITED",
        code="SGX_REAL_0048",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI ELECTRICITY MUMBAI LIMITED",
        code="SGX_REAL_0049",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI ENTERPRISES LIMITED",
        code="SGX_REAL_0050",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI GREEN ENERGY LIMITED",
        code="SGX_REAL_0051",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI GREEN ENERGY (UP) LIMITED",
        code="SGX_REAL_0052",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI INTERNATIONAL CONTAINER TERMINAL PRIVATE LIMITED",
        code="SGX_REAL_0053",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI PORTS AND SPECIAL ECONOMIC ZONE LIMITED",
        code="SGX_REAL_0054",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI RENEWABLE ENERGY (RJ) LIMITED ",
        code="SGX_REAL_0055",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADANI TRANSMISSION LIMITED",
        code="SGX_REAL_0056",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADARO FINANCE B.V. ",
        code="SGX_REAL_0057",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADD HERO HOLDINGS LIMITED",
        code="SGX_REAL_0058",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADDVALUE TECHNOLOGIES LTD",
        code="SGX_REAL_0059",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADECOAGRO S.A.",
        code="SGX_REAL_0060",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADM AG HOLDING LIMITED",
        code="SGX_REAL_0061",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADROIT INNOVATIONS LIMITED ",
        code="SGX_REAL_0062",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCE AGRO PUBLIC COMPANY LIMITED",
        code="SGX_REAL_0063",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCED HOLDINGS LTD.",
        code="SGX_REAL_0064",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCED INFO SERVICE PUBLIC COMPANY LIMITED",
        code="SGX_REAL_0065",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCED INTEGRATED MANUFACTURING CORP. LTD.",
        code="SGX_REAL_0066",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCED SEMICONDUCTOR ENGINEERING, INC",
        code="SGX_REAL_0067",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCED SYSTEMS AUTOMATION LIMITED",
        code="SGX_REAL_0068",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCE MODULES GROUP LIMITED",
        code="SGX_REAL_0069",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANCE SCT LIMITED",
        code="SGX_REAL_0070",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANTA INDIA LIMITED",
        code="SGX_REAL_0071",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANTA LIMITED",
        code="SGX_REAL_0072",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANTA LIMITED GDR",
        code="SGX_REAL_0073",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVANTEST CORPORATION",
        code="SGX_REAL_0074",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ADVENTUS HOLDINGS LIMITED",
        code="SGX_REAL_0075",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AED OIL LIMITED",
        code="SGX_REAL_0076",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEGEA FINANCE S.A R.L.",
        code="SGX_REAL_0077",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEI CORPORATION LTD.",
        code="SGX_REAL_0078",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEM-EVERTECH HOLDINGS LTD",
        code="SGX_REAL_0079",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEM HOLDINGS LTD.",
        code="SGX_REAL_0080",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AENZA S.A.A.",
        code="SGX_REAL_0081",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEON CREDIT SERVICE CO., LTD.",
        code="SGX_REAL_0082",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEON FINANCIAL SERVICE CO., LTD.",
        code="SGX_REAL_0083",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AERKOMM INC.",
        code="SGX_REAL_0084",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEROPUERTO INTERNACIONAL DE TOCUMEN, S.A.",
        code="SGX_REAL_0085",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEROSPACE SATELLITE CORPORATION HOLDING B.V.",
        code="SGX_REAL_0086",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AE ROTOR HOLDING B.V.",
        code="SGX_REAL_0087",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AE ROTOR HOLDING B.V. NETHERLANDS",
        code="SGX_REAL_0088",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEROVIAS DE MEXICO, S.A. DE C.V.",
        code="SGX_REAL_0089",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AES ANDES S.A.",
        code="SGX_REAL_0090",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AES CHINA GENERATING CO. LTD",
        code="SGX_REAL_0091",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AES PANAMA GENERATION HOLDINGS S.R.L.",
        code="SGX_REAL_0092",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AEV INTERNATIONAL PTE. LTD. ",
        code="SGX_REAL_0093",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AFFIN BANK BERHAD",
        code="SGX_REAL_0094",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AF GLOBAL LIMITED",
        code="SGX_REAL_0095",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AFOR LIMITED",
        code="SGX_REAL_0096",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AFP PROPERTIES LIMITED",
        code="SGX_REAL_0097",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AFTERPAY LIMITED",
        code="SGX_REAL_0098",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGEAS CAPITAL (ASIA) LIMITED",
        code="SGX_REAL_0099",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGF CANADIAN GROWTH EQUITY FUND LIMITED",
        code="SGX_REAL_0100",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGI FINANCE PTY LIMITED",
        code="SGX_REAL_0101",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGILE GROUP HOLDINGS LIMITED",
        code="SGX_REAL_0102",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGILE PROPERTY HOLDINGS LIMITED",
        code="SGX_REAL_0103",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGRICULTURAL BANK OF CHINA LIMITED, SINGAPORE BRANCH",
        code="SGX_REAL_0104",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGRICULTURAL DEVELOPMENT BANK OF CHINA",
        code="SGX_REAL_0105",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGVA CORPORATION LIMITED",
        code="SGX_REAL_0106",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AGV GROUP LIMITED",
        code="SGX_REAL_0107",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AI FINANCE B.V",
        code="SGX_REAL_0108",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIMS AMP CAPITAL INDUSTRIAL REIT",
        code="SGX_REAL_0109",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIMS AMP CAPITAL INDUSTRIAL REIT MANAGEMENT LIMITED",
        code="SGX_REAL_0110",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIMS APAC REIT MANAGEMENT LIMITED",
        code="SGX_REAL_0111",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIMS PROPERTY SECURITIES FUND",
        code="SGX_REAL_0112",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIROCEAN GROUP LIMITED",
        code="SGX_REAL_0113",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AIR WATER INC.",
        code="SGX_REAL_0114",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AJJ MEDTECH HOLDINGS LIMITED",
        code="SGX_REAL_0115",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALAM SUTERA INTERNATIONAL PRIVATE LIMITED",
        code="SGX_REAL_0116",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALAM SYNERGY PTE LTD.",
        code="SGX_REAL_0117",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALANTAC TECHNOLOGY LTD",
        code="SGX_REAL_0118",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALBEDO LIMITED",
        code="SGX_REAL_0119",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AL CANDELARIA (SPAIN), S.L.U.",
        code="SGX_REAL_0120",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALFA DESARROLLO SPA",
        code="SGX_REAL_0121",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALIBABA GROUP HOLDING LIMITED",
        code="SGX_REAL_0122",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALIBABA PICTURES GROUP LIMITED",
        code="SGX_REAL_0123",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALITA RESOURCES LIMITED",
        code="SGX_REAL_0124",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLCO COMMERCIAL REAL ESTATE INVESTMENT TRUST",
        code="SGX_REAL_0125",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLGREEN PROPERTIES LIMITED",
        code="SGX_REAL_0126",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLGREEN TREASURY PTE. LTD. ",
        code="SGX_REAL_0127",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLIANCE GLOBAL GROUP CAYMAN ISLANDS , INC ",
        code="SGX_REAL_0128",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLIANCE GLOBAL GROUP CAYMAN ISLANDS, INC.",
        code="SGX_REAL_0129",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLIANCE HEALTHCARE GROUP LIMITED",
        code="SGX_REAL_0130",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLIANCE MINERAL ASSETS LIMITED",
        code="SGX_REAL_0131",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALLIED TECHNOLOGIES LIMITED",
        code="SGX_REAL_0132",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALL-LINK AIR & SEA LIMITED",
        code="SGX_REAL_0133",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPHA DX GROUP LIMITED",
        code="SGX_REAL_0134",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPHA ENERGY HOLDINGS LIMITED",
        code="SGX_REAL_0135",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPHA HOLDING, S.A. DE C.V.",
        code="SGX_REAL_0136",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPHA INTEGRATED REIT MANAGEMENT PTE. LTD.",
        code="SGX_REAL_0137",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPINA HOLDINGS LIMITED",
        code="SGX_REAL_0138",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALPS ELECTRIC CO., LTD.",
        code="SGX_REAL_0139",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALSEA, S.A.B DE C.V.",
        code="SGX_REAL_0140",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALSET INTERNATIONAL LIMITED",
        code="SGX_REAL_0141",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALTUS CAPITAL PTE LTD.",
        code="SGX_REAL_0142",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ALUMINA FINANCE LIMITED",
        code="SGX_REAL_0143",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMAGGI LUXEMBOURG INTERNATIONAL S. A R.L.  ",
        code="SGX_REAL_0144",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMA GROUP LIMITED",
        code="SGX_REAL_0145",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMARA HOLDINGS LIMITED",
        code="SGX_REAL_0146",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMBANK (M) BERHAD",
        code="SGX_REAL_0147",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMBB Capital (L) Ltd",
        code="SGX_REAL_0148",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMBIPAR LUX S.A R.L.",
        code="SGX_REAL_0149",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMBIQ MICRO, INC.",
        code="SGX_REAL_0150",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMCOR LIMITED",
        code="SGX_REAL_0151",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMCORP GLOBAL LIMITED",
        code="SGX_REAL_0152",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMERICA MOVIL, S.A.B. DE C.V.",
        code="SGX_REAL_0153",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMOS GROUP LIMITED",
        code="SGX_REAL_0154",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMOVA ASIA LIMITED VCC",
        code="SGX_REAL_0155",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMOVA ASSET MANAGEMENT ASIA LIMITED",
        code="SGX_REAL_0156",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMP BANK LIMITED",
        code="SGX_REAL_0157",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMP GROUP FINANCE SERVICES LIMITED",
        code="SGX_REAL_0158",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMPLEFIELD LIMITED",
        code="SGX_REAL_0159",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMP LIMITED",
        code="SGX_REAL_0160",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMTD IDEA GROUP",
        code="SGX_REAL_0161",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMTD INTERNATONAL INC.",
        code="SGX_REAL_0162",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMTEK AUTO LIMITED",
        code="SGX_REAL_0163",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMTEK ENGINEERING LTD",
        code="SGX_REAL_0164",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMTEK INDIA LIMITED",
        code="SGX_REAL_0165",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMUNDI ASSET MANAGEMENT",
        code="SGX_REAL_0166",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AMUNDI HONG KONG LIMITED",
        code="SGX_REAL_0167",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANA HOLDINGS INC.",
        code="SGX_REAL_0168",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANAN INTERNATIONAL LIMITED",
        code="SGX_REAL_0169",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANCHOR RESOURCES LIMITED",
        code="SGX_REAL_0170",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANCHUN INTERNATIONAL HOLDINGS LTD.",
        code="SGX_REAL_0171",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANG AUTO LIMITED",
        code="SGX_REAL_0172",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANGLOGOLD ASHANTI HOLDINGS FINANCE PLC",
        code="SGX_REAL_0173",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANHUI TRANSPORTATION HOLDING GROUP (H.K.) LIMITED",
        code="SGX_REAL_0174",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANKUR DRUGS AND PHARMA LIMITED",
        code="SGX_REAL_0175",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANLLIAN CAPITAL 2 LIMITED",
        code="SGX_REAL_0176",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANLLIAN CAPITAL LIMITED",
        code="SGX_REAL_0177",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANNAIK LIMITED",
        code="SGX_REAL_0178",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANNICA HOLDINGS LIMITED",
        code="SGX_REAL_0179",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANRITSU CORPORATION",
        code="SGX_REAL_0180",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANSTOCK II LIMITED",
        code="SGX_REAL_0181",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANTAM FINANCE LIMITED",
        code="SGX_REAL_0182",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ANWELL TECHNOLOGIES LIMITED",
        code="SGX_REAL_0183",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AOXIN Q & M DENTAL GRP LIMITED",
        code="SGX_REAL_0184",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AOZORA BANK, LTD.",
        code="SGX_REAL_0185",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APAC REALTY LIMITED",
        code="SGX_REAL_0186",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APA INFRASTRUCTURE LIMITED",
        code="SGX_REAL_0187",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APEIRON AGROCOMMODITIES PTE. LTD.",
        code="SGX_REAL_0188",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APEX-PAL INTERNATIONAL LTD",
        code="SGX_REAL_0189",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APL REALTY HOLDINGS PTE. LTD.",
        code="SGX_REAL_0190",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AP OIL INTERNATIONAL LIMITED",
        code="SGX_REAL_0191",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APOLLO ENTERPRISES LIMITED",
        code="SGX_REAL_0192",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APT PIPELINES LIMITED",
        code="SGX_REAL_0193",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="APTT MANAGEMENT PTE. LIMITED",
        code="SGX_REAL_0194",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AQUA-TERRA SUPPLY CO. LIMITED",
        code="SGX_REAL_0195",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA ASSET MANAGEMENT (FORTUNE) LIMITED",
        code="SGX_REAL_0196",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA ASSET MANAGEMENT LIMITED",
        code="SGX_REAL_0197",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA-CWT TRUST MANAGEMENT (CACHE) LIMITED",
        code="SGX_REAL_0198",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA LOGOS LOGISTICS TRUST MANAGEMENT LIMITED",
        code="SGX_REAL_0199",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA TRUST MANAGEMENT (CACHE) LIMITED",
        code="SGX_REAL_0200",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA TRUST MANAGEMENT (SUNTEC) LIMITED",
        code="SGX_REAL_0201",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARA TRUST MANAGEMENT (USH) PTE. LTD.",
        code="SGX_REAL_0202",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AREIF (SINGAPORE I) PTE. LTD.",
        code="SGX_REAL_0203",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARIANECORP LIMITED",
        code="SGX_REAL_0204",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARION ENTERTAINMENT SINGAPORE LIMITED",
        code="SGX_REAL_0205",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARMARDA GROUP LIMITED",
        code="SGX_REAL_0206",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARMF (WHITESANDS) PTE. LTD. ",
        code="SGX_REAL_0207",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARMSTRONG INDUSTRIAL CORP LTD",
        code="SGX_REAL_0208",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARPENI PRATAMA OCEAN LINE INVESTMENT B.V.",
        code="SGX_REAL_0209",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARTIVISION TECHNOLOGIES LTD.",
        code="SGX_REAL_0210",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ARWEN INVESTMENT CORPORATION LIMITED",
        code="SGX_REAL_0211",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASA GROUP HOLDINGS LTD",
        code="SGX_REAL_0212",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASAHI BREWERIES, LTD.",
        code="SGX_REAL_0213",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASAHI GLASS COMPANY LIMITED",
        code="SGX_REAL_0214",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASAHI GROUP HOLDINGS, LTD.",
        code="SGX_REAL_0215",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASAHI MUTUAL LIFE INSURANCE COMPANY",
        code="SGX_REAL_0216",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASAHI REFINING USA INC.",
        code="SGX_REAL_0217",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS FUNDS MANAGEMENT (S) LIMITED",
        code="SGX_REAL_0218",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS HOSPITALITY FUND MANAGEMENT PTE. LTD.",
        code="SGX_REAL_0219",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS HOSPITALITY MTN PTE. LTD. ",
        code="SGX_REAL_0220",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS PROPERTY FUND TRUSTEE PTE. LTD.",
        code="SGX_REAL_0221",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENDAS PTE LTD",
        code="SGX_REAL_0222",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCENT BRIDGE LIMITED",
        code="SGX_REAL_0223",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCIANO FINANCE LIMITED",
        code="SGX_REAL_0224",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCOTT REIT MTN (EURO) PTE. LTD.",
        code="SGX_REAL_0225",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="Ascott REIT MTN PTE. LTD.",
        code="SGX_REAL_0226",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCOTT REIT MTN PTE LTD",
        code="SGX_REAL_0227",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASCOTT RESIDENCE TRUST MANAGEMENT LIMITED",
        code="SGX_REAL_0228",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASEAN CITY (BVI) LIMITED",
        code="SGX_REAL_0229",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASE TECHNOLOGY HOLDING CO., LTD.",
        code="SGX_REAL_0230",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ALUMINUM HOLDINGS LIMITED",
        code="SGX_REAL_0231",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA CEMENT CORPORATION",
        code="SGX_REAL_0232",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIACITI TRUST SINGAPORE PTE. LTD.",
        code="SGX_REAL_0233",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA DEKOR HOLDINGS LIMITED",
        code="SGX_REAL_0234",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ENTERPRISES HOLDING LIMITED",
        code="SGX_REAL_0235",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA ENVIRONMENT HOLDINGS LTD",
        code="SGX_REAL_0236",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA FASHION HOLDINGS LIMITED",
        code="SGX_REAL_0237",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA FOOD & PROPERTIES LIMITED",
        code="SGX_REAL_0238",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAMEDIC LIMITED",
        code="SGX_REAL_0239",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAN DEVELOPMENT BAN",
        code="SGX_REAL_0240",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAN DEVELOPMENT BANK",
        code="SGX_REAL_0241",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAN HEALTHCARE SPECIALISTS LIMITED",
        code="SGX_REAL_0242",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAN MICRO HOLDINGS LIMITED",
        code="SGX_REAL_0243",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA PACIFIC BREWERIES",
        code="SGX_REAL_0244",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA PACIFIC BREWERIES LIMITED",
        code="SGX_REAL_0245",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA PACIFIC PORTS DEVELOPMENT COMPANY LIMITED",
        code="SGX_REAL_0246",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA-PACIFIC STRATEGIC INVESTMENTS LIMITED",
        code="SGX_REAL_0247",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAPHARM GROUP LTD.",
        code="SGX_REAL_0248",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIAPHOS LIMITED",
        code="SGX_REAL_0249",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA POWER CORPORATION LIMITED",
        code="SGX_REAL_0250",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA SILK HOLDINGS LIMITED",
        code="SGX_REAL_0251",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIASONS CAPITAL LIMITED",
        code="SGX_REAL_0252",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIASONS WFG FINANCIAL LTD ",
        code="SGX_REAL_0253",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIATIC GROUP (HOLDINGS) LIMITED",
        code="SGX_REAL_0254",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA TIGER GROUP LIMITED",
        code="SGX_REAL_0255",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIATRAVEL.COM HOLDINGS LTD",
        code="SGX_REAL_0256",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA VETS HOLDINGS LTD.",
        code="SGX_REAL_0257",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASIA WATER TECHNOLOGY LTD",
        code="SGX_REAL_0258",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASICS CORPORATION",
        code="SGX_REAL_0259",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASJ HOLDINGS LIMITED",
        code="SGX_REAL_0260",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASL MARINE HOLDINGS LTD.",
        code="SGX_REAL_0261",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="A-SMART HOLDINGS LTD.",
        code="SGX_REAL_0262",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="A-SONIC AEROSPACE LIMITED",
        code="SGX_REAL_0263",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASPEN (GROUP) HOLDINGS LIMITED",
        code="SGX_REAL_0264",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASPIAL CORPORATION LIMITED",
        code="SGX_REAL_0265",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASPIAL LIFESTYLE LIMITED",
        code="SGX_REAL_0266",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASPIAL TREASURY PTE. LTD.",
        code="SGX_REAL_0267",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASSAM COMPANY LIMITED",
        code="SGX_REAL_0268",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASSURANCE HEALTHCARE LIMITED",
        code="SGX_REAL_0269",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTAKA HOLDINGS LIMITED",
        code="SGX_REAL_0270",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTI HOLDINGS LIMITED",
        code="SGX_REAL_0271",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA 7 PTE. LTD.",
        code="SGX_REAL_0272",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA 8 PTE. LTD.",
        code="SGX_REAL_0273",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA 9 PTE. LTD.",
        code="SGX_REAL_0274",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA III PTE. LTD.",
        code="SGX_REAL_0275",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA IV PTE. LTD.",
        code="SGX_REAL_0276",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA VI PTE. LTD.",
        code="SGX_REAL_0277",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASTREA V PTE. LTD.",
        code="SGX_REAL_0278",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ASUSTEK COMPUTER INC.",
        code="SGX_REAL_0279",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ATENTO LUXCO 1, S.A.",
        code="SGX_REAL_0280",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ATLANTIC NAVIGATION HOLDINGS (SINGAPORE) LIMITED",
        code="SGX_REAL_0281",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ATTIKA GROUP LTD.",
        code="SGX_REAL_0282",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="ATTILAN GROUP LIMITED",
        code="SGX_REAL_0283",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUCKLAND COUNCIL",
        code="SGX_REAL_0284",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUDIENCE ANALYTICS LIMITED",
        code="SGX_REAL_0285",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="Auna S.A.",
        code="SGX_REAL_0286",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUNA S.A.A.",
        code="SGX_REAL_0287",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUNA S.A., ONCOSALUD S.A.C.",
        code="SGX_REAL_0288",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AU OPTRONICS CORP",
        code="SGX_REAL_0289",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AURIC PACIFIC GROUP LIMITED",
        code="SGX_REAL_0290",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AURIZON NETWORK PTY LTD",
        code="SGX_REAL_0291",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUROBINDO PHARMA LIMITED",
        code="SGX_REAL_0292",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSDRILL FINANCE PTY LTD",
        code="SGX_REAL_0293",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSGRID FINANCE PTY LIMITED",
        code="SGX_REAL_0294",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSGROUP LIMITED",
        code="SGX_REAL_0295",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSNET SERVICES",
        code="SGX_REAL_0296",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSNET SERVICES HOLDINGS PTY LTD",
        code="SGX_REAL_0297",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSNET SERVICES LTD",
        code="SGX_REAL_0298",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSSINO GROUP LTD",
        code="SGX_REAL_0299",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSTON INTERNATIONAL GROUP LTD",
        code="SGX_REAL_0300",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSTRALAND PROPERTY GROUP",
        code="SGX_REAL_0301",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSTRALIAN METCOAL FINANCING PTY LTD",
        code="SGX_REAL_0302",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSTRALIA PACIFIC AIRPORTS (MELBOURNE) PTY LIMITED",
        code="SGX_REAL_0303",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUSWIN HOLDINGS LIMITED",
        code="SGX_REAL_0304",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUTAGCO LTD.",
        code="SGX_REAL_0305",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUTOMATED TOUCHSTONE MACHINES LIMITED",
        code="SGX_REAL_0306",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUTOPISTAS DEL SOL, S.A.",
        code="SGX_REAL_0307",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AUTRON CORPORATION LIMITED",
        code="SGX_REAL_0308",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVAPLAS LTD",
        code="SGX_REAL_0309",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVARGA LIMITED",
        code="SGX_REAL_0310",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVATION CAPITAL S.A.",
        code="SGX_REAL_0311",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVATION GROUP (S) PTE. LTD.",
        code="SGX_REAL_0312",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVEO GROUP LIMITED",
        code="SGX_REAL_0313",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVEPOINT, INC.",
        code="SGX_REAL_0314",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIANCA HOLDINGS S.A. ",
        code="SGX_REAL_0315",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIATION CAPITAL GROUP CORP.",
        code="SGX_REAL_0316",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVICADE SYSTEMS (UK) LIMITED",
        code="SGX_REAL_0317",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIC INTERNATIONAL INVESTMENTS LIMITED",
        code="SGX_REAL_0318",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIC INTERNATIONAL LEASING CO., LTD.",
        code="SGX_REAL_0319",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIC INTERNATIONAL MARITIME HOLDINGS LIMITED",
        code="SGX_REAL_0320",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVI FUNDING COMPANY LIMITED",
        code="SGX_REAL_0321",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVI-TECH ELECTRONICS LIMITED",
        code="SGX_REAL_0322",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVI-TECH HOLDINGS LIMITED",
        code="SGX_REAL_0323",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIVA SINGLIFE HOLDING PTE. LTD.",
        code="SGX_REAL_0324",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVIVA SINGLIFE HOLDINGS PTE. LTD.",
        code="SGX_REAL_0325",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AVJENNINGS LIMITED",
        code="SGX_REAL_0326",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXCELASIA INC.",
        code="SGX_REAL_0327",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXIATA SPV2 BERHAD",
        code="SGX_REAL_0328",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXIATA SPV5 (LABUAN) LIMITED",
        code="SGX_REAL_0329",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXINGTON INC.",
        code="SGX_REAL_0330",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXIS BANK LIMITED",
        code="SGX_REAL_0331",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXIS BANK LIMITED (ACTING THROUGH ITS DUBAI INTERNATIONAL FINANCIAL CENTRE BRANCH)",
        code="SGX_REAL_0332",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AXIS BANK LIMITED, ACTING THROUGH ITS GIFT CITY BRANCH",
        code="SGX_REAL_0333",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AYC FINANCE LIMITED",
        code="SGX_REAL_0334",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="Ayondo Ltd.",
        code="SGX_REAL_0335",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZEUS SYSTEMS HOLDINGS LTD.",
        code="SGX_REAL_0336",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZION BAO PTE. LTD.",
        code="SGX_REAL_0337",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZTECH GLOBAL LTD.",
        code="SGX_REAL_0338",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZTECH GROUP LTD.",
        code="SGX_REAL_0339",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZTECH SYSTEMS LTD",
        code="SGX_REAL_0340",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZUL INVESTMENTS LLP",
        code="SGX_REAL_0341",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZUL SECURED FINANCE LLP",
        code="SGX_REAL_0342",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZURE POWER ENERGY LTD",
        code="SGX_REAL_0343",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="AZURE POWER SOLAR ENERGY PRIVATE LIMITED",
        code="SGX_REAL_0344",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BABCOCK & BROWN GLOBAL INV LTD",
        code="SGX_REAL_0345",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BABCOCK&BROWN STRUC FIN FD LTD",
        code="SGX_REAL_0346",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BACUI TECHNOLOGIES INTERNATIONAL LTD.",
        code="SGX_REAL_0347",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAGAN CAPITAL LTD",
        code="SGX_REAL_0348",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAIDU, INC.",
        code="SGX_REAL_0349",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAKER TECHNOLOGY LIMITED",
        code="SGX_REAL_0350",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAKRIE TELECOM PTE. LTD.",
        code="SGX_REAL_0351",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BALLARPUR INDUSTRIES LIMITED",
        code="SGX_REAL_0352",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BALLARPUR INTERNATIONAL GRAPHIC PAPER HOLDINGS B.V.",
        code="SGX_REAL_0353",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BALLURPUR INTERNATIONAL GRAPHIC PAPER HOLDINGS B.V.",
        code="SGX_REAL_0354",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO BILBAO VIZCAYA ARGENTARIA, S.A.",
        code="SGX_REAL_0355",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO DAVIVIENDA S.A.",
        code="SGX_REAL_0356",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO DE GALICIA Y BUENOS AIRES S.A.U.",
        code="SGX_REAL_0357",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO DE ORO UNIVERSAL BANK",
        code="SGX_REAL_0358",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO GENERAL, S.A.",
        code="SGX_REAL_0359",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO INDUSTRIAL, S.A.",
        code="SGX_REAL_0360",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO ITAU CHILE, ACTING THROUGH ITAU CHILE NEW YORK BRANCH",
        code="SGX_REAL_0361",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCOLOMBIA S.A.",
        code="SGX_REAL_0362",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO MERCANTIL DEL NORTE, S.A. (CAYMAN ISLANDS BRANCH)",
        code="SGX_REAL_0363",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO MERCANTIL DEL NORTE,S.A,INSTITUCION DE BANCA MULTIPLE,GRUPO FINANCIERO BANORTE(CAYMAN IS BR)",
        code="SGX_REAL_0364",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO NACIONAL DE COMERCIO EXTERIOR,SOCIEDAD NACIONAL DE CREDITO,INSTITUCION DE BANCA DE DESARROLLO",
        code="SGX_REAL_0365",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO SANTANDER MEXICO, S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINANCIERO SANTANDER MEXICO",
        code="SGX_REAL_0366",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANCO SANTANDER TOTTA, S.A.,",
        code="SGX_REAL_0367",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGKOK BANK PUBLIC COMPANY LIMITED (ACTING THROUGH ITS HONG KONG BRANCH)",
        code="SGX_REAL_0368",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGKOK DUSIT MEDICAL SERVICES PUBLIC COMPANY LIMITED",
        code="SGX_REAL_0369",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANGLALINK DIGITAL COMMUNICATIONS LIMITED",
        code="SGX_REAL_0370",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANISTMO S.A.",
        code="SGX_REAL_0371",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAN JOO & COMPANY LIMITED",
        code="SGX_REAL_0372",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF AYUDHYA PUBLIC COMPANY LIMITED",
        code="SGX_REAL_0373",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF BARODA",
        code="SGX_REAL_0374",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF BARODA ACTING THROUGH ITS INTERNATIONAL FINANCIAL SERVICE CENTRE BANKING UNIT AT GIFT CITY",
        code="SGX_REAL_0375",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF CEYLON",
        code="SGX_REAL_0376",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF CHINA, ABU DHABI BRANCH",
        code="SGX_REAL_0377",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF CHINA LIMITED, SINGAPORE BRANCH",
        code="SGX_REAL_0378",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF CHINA, SINGAPORE BRANCH",
        code="SGX_REAL_0379",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF CHINA, TAIPEI BRANCH",
        code="SGX_REAL_0380",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF INDIA",
        code="SGX_REAL_0381",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF INDIA, LONDON BRANCH",
        code="SGX_REAL_0382",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF NEW YORK MELLON",
        code="SGX_REAL_0383",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK OF THE PHILIPPINE ISLANDS",
        code="SGX_REAL_0384",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANK VONTOBEL AG",
        code="SGX_REAL_0385",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAN LEONG TECHNOLOGIES LIMITED",
        code="SGX_REAL_0386",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BANYAN TREE HOLDINGS LIMITED",
        code="SGX_REAL_0387",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAOSTEEL GROUP CORPORATION",
        code="SGX_REAL_0388",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAOXIN AUTO FINANCE I LIMITED",
        code="SGX_REAL_0389",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BARCLAYS BANK PLC",
        code="SGX_REAL_0390",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BARMINCO FINANCE PTY LIMITED",
        code="SGX_REAL_0391",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BARTRONICS INDIA LIMITED",
        code="SGX_REAL_0392",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BASF IRELAND DAC",
        code="SGX_REAL_0393",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAVARIAN SKY KOREAN AUTO RECEIVABLES 1 PTE. LTD.",
        code="SGX_REAL_0394",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAY AREA GOLD GROUP LIMITED",
        code="SGX_REAL_0395",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT IABS IX PTE. LTD.",
        code="SGX_REAL_0396",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT IABS VIII PTE. LTD.",
        code="SGX_REAL_0397",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT IABS VII PTE. LTD.",
        code="SGX_REAL_0398",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT INFRASTRUCTURE CAPITAL III PTE. LTD.",
        code="SGX_REAL_0399",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT INFRASTRUCTURE CAPITAL II PTE. LTD.",
        code="SGX_REAL_0400",
        priority="normal",
        sector="Unknown",
    ),
    Company(
        name="BAYFRONT INFRASTRUCTURE CAPITAL IV PTE. LTD.",
        code="SGX_REAL_0401",
        priority="normal",
        sector="Unknown",
    ),
]
